---
# Setting "-e reset=1" on command line force clean build and upgrades.
reset: false

dump_file: dz.{{inventory_hostname}}.pgdump.gz
backup_dir: "{{ lookup('env', 'HOME') }}/setup/backup"

# Build parameters used by multiple hosts:
win_setup_dir: 'C:\abyss\temp'

local_src_dir: "{{ inventory_dir|dirname }}"
local_work_dir: "{{ local_src_dir }}/temp"
local_dist_dir: "{{ local_src_dir }}/dist"

local_temp: /tmp/ansible-tmp_{{ inventory_hostname }}_{{ ansible_date_time.iso8601|replace(':','-') }}
...
