# Note: Since 2015 newer travis repositories build on so called container
#       environment without sudo support. That's fine, I don't need sudo but...
# Beware: Travis YAML validator _may_ fail with "Error creating build script"
#         even when it finds the "sudo" word *within yaml comments*!
# See: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

language: python
python:
  - 2.7
services:
  - postgresql
env:
  global:
    # Note: Django test will prepend database name "dz" with "test_".
    - DATABASE_URL=postgres://postgres@localhost/dz
cache: pip
install:
  # Upgrade preinstalled pip v6 to v8, which supports wheel caching:
  - pip install -U pip==8.1.2 wheel==0.29.0
  - pip install -r requirements/devel.txt
before_script:
  # As travis provides privileged postgres user, django test script can create
  # and drop test databases, so `createdb -U postgres test_dz` is not needed.
  - python manage.py compilemessages
  # Prepare static assets for all skins under test.
  # Use `-v0` to silence verbose whitenoise messages.
  - env DZ_SKIN=plus      python manage.py collectstatic --noinput -v0
  - env DZ_SKIN=grappelli python manage.py collectstatic --noinput -v0
  - env DZ_SKIN=bootstrap python manage.py collectstatic --noinput -v0
script:
  # Use `-v2` to log individual tests. Unlike `make.sh`, don't use `--keep`.
  - coverage run --source=. --omit='*/bot/*' manage.py test -v2
after_success:
  - coveralls
