---
ansible_host: "{{ secret.hosts.win7hop32.hostname }}"
ansible_user: "{{ secret.hosts.win7hop32.username }}"
ansible_password: "{{ secret.hosts.win7hop32.password }}"
ansible_port: "{{ secret.hosts.win7hop32.port  }}"
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

# per-host bot settings:
bot_server_name: "{{ secret.hosts.top_new.dz_name }}.{{ secret.hosts.top_new.nginx_base_url }}"
bot_api_url: "{{ secret.settings.api_url }}"
bot_secret_key: "{{ secret.settings.spider_secret_key }}"
...
