---
- name: install bot package
  tags: install-bot
  hosts: windows-prod
  vars:
    install_script: dz-bot-install.{{inventory_hostname}}.ps1
    dist_files:
      - "{{install_script}}"
      - dz-bot-dist.zip
      - unzip.exe

  tasks:
    - name: update installer script
      delegate_to: localhost
      template: src=../templates/install-bot.ps1.j2
                dest={{local_dist_dir}}/{{install_script}}

    - name: verify that distribution is ready
      delegate_to: localhost
      stat: path="{{local_dist_dir}}/{{item}}"
      with_items: "{{ dist_files }}"
      register: _stat_dist

    - assert:
        that: _stat_dist.results|selectattr('stat.exists')|list|length == dist_files|length
        msg: You must prepare bot distribution in advance

    - win_file: path="{{win_setup_dir}}" state=directory

    - name: upload distribution files
      win_copy: src="{{local_dist_dir}}/{{item}}" dest="{{win_setup_dir}}"
      with_items: "{{ dist_files }}"

    - name: run install script
      script: "{{local_dist_dir}}/{{install_script}}"
      register: _run_install

    # The `replace` trick filters out junk unicode mixed in by remote powershell.
    - debug: msg="{{ _run_install.stdout_lines | map('replace', '\u0000', '') | list }}"
...
