# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='crawl id (column)')),
                ('target', models.CharField(choices=[(b'news', 'news (crawl target)'), (b'tips', 'tips (crawl target)')], db_index=True, max_length=6, verbose_name='crawl target (column)')),
                ('manual', models.NullBooleanField(db_index=True, verbose_name='crawl type (column)')),
                ('status', models.CharField(max_length=10, verbose_name='crawl status (column)')),
                ('started', models.DateTimeField(null=True, verbose_name='started at (column)')),
                ('ended', models.DateTimeField(null=True, verbose_name='ended at (column)')),
                ('count', models.SmallIntegerField(default=0, verbose_name='no. of items (column)')),
                ('host', models.CharField(db_index=True, max_length=24, verbose_name='hostname (column)')),
                ('pid', models.CharField(max_length=6, verbose_name='crawler pid (column)')),
            ],
            options={
                'verbose_name': 'crawl (table)',
                'verbose_name_plural': 'crawls (table)',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='news id (column)')),
                ('link', models.URLField(verbose_name='news link (column)')),
                ('title', models.CharField(max_length=150, verbose_name='news title (column)')),
                ('sport', models.CharField(db_index=True, max_length=20, verbose_name='sport (column)')),
                ('league', models.CharField(db_index=True, max_length=80, verbose_name='league (column)')),
                ('parties', models.CharField(max_length=80, verbose_name='parties (column)')),
                ('published', models.DateTimeField(verbose_name='published (column)')),
                ('updated', models.DateTimeField(db_index=True, verbose_name='updated (column)')),
                ('crawled', models.DateTimeField(verbose_name='fetched (column)')),
                ('archived', models.BooleanField(verbose_name='archived (column)')),
                ('preamble', models.CharField(max_length=500, null=True, verbose_name='news preamble (column)')),
                ('content', models.TextField(verbose_name='full news content (column)')),
                ('subtable', models.TextField(verbose_name='news subtable (column)')),
            ],
            options={
                'permissions': [('crawl_news', 'Can crawl news'), ('view_news', 'Can only view news')],
                'verbose_name': 'news (table)',
                'verbose_name_plural': 'many news (table)',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='start time (column)')),
                ('target', models.CharField(choices=[(b'news', 'news (crawl target)'), (b'tips', 'tips (crawl target)')], max_length=6, verbose_name='target (column)')),
            ],
            options={
                'verbose_name': 'schedule item (table)',
                'verbose_name_plural': 'schedule (table)',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='tip id (column)')),
                ('league', models.CharField(db_index=True, max_length=40, verbose_name='tip league (column)')),
                ('parties', models.CharField(db_index=True, max_length=150, verbose_name='tip parties (column)')),
                ('title', models.CharField(max_length=60, verbose_name='tip title (column)')),
                ('betting', models.CharField(max_length=32, verbose_name='betting (column)')),
                ('odds', models.CharField(max_length=6, verbose_name='tip odds (column)')),
                ('min_odds', models.CharField(max_length=6, verbose_name='minimum tip odds (column)')),
                ('result', models.CharField(max_length=15, verbose_name='tip result (column)')),
                ('earnings', models.CharField(max_length=8, verbose_name='earnings (column)')),
                ('spread', models.CharField(max_length=8, verbose_name='spread (column)')),
                ('stake', models.CharField(max_length=8, verbose_name='stake (column)')),
                ('success', models.CharField(max_length=12, null=True, verbose_name='tip success (column)')),
                ('tipster', models.CharField(db_index=True, max_length=12, verbose_name='tipster (column)')),
                ('published', models.DateTimeField(db_index=True, null=True, verbose_name='published (column)')),
                ('updated', models.DateTimeField(verbose_name='updated (column)')),
                ('crawled', models.DateTimeField(verbose_name='fetched (column)')),
                ('link', models.URLField(verbose_name='tip link (column)')),
                ('archived', models.BooleanField(verbose_name='archived (column)')),
                ('text', models.TextField(null=True, verbose_name='tip text (column)')),
            ],
            options={
                'permissions': [('crawl_tips', 'Can crawl tips'), ('view_tips', 'Can only view tips')],
                'verbose_name': 'tip (table)',
                'verbose_name_plural': 'tips (table)',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dz_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='dz user name')),
                ('password', models.CharField(max_length=64, verbose_name='dz user password')),
                ('is_admin', models.BooleanField(verbose_name='is dz administrator')),
            ],
            options={
                'verbose_name': 'dz user',
                'verbose_name_plural': 'dz users',
            },
        ),
        migrations.AlterIndexTogether(
            name='tip',
            index_together=set([('published', 'archived')]),
        ),
        migrations.AlterIndexTogether(
            name='news',
            index_together=set([('published', 'archived')]),
        ),
    ]
