# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='crawl id')),
                ('type', models.CharField(choices=[('manual', 'manual crawl'), ('auto', 'auto crawl')], max_length=8, verbose_name='crawl type')),
                ('action', models.CharField(choices=[('news', 'news crawl'), ('tips', 'tips crawl')], max_length=6, verbose_name='crawl target')),
                ('status', models.CharField(max_length=10, verbose_name='crawl status')),
                ('started', models.DateTimeField(verbose_name='started at')),
                ('ended', models.DateTimeField(null=True, verbose_name='ended at')),
                ('news', models.SmallIntegerField(verbose_name='no. of news')),
                ('tips', models.SmallIntegerField(verbose_name='no. of tips')),
                ('host', models.CharField(max_length=24, verbose_name='hostname')),
                ('ipaddr', models.CharField(max_length=20, verbose_name='ip address')),
                ('pid', models.CharField(max_length=6, verbose_name='crawler pid')),
            ],
            options={
                'verbose_name': 'crawl',
                'verbose_name_plural': 'crawls',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='news id')),
                ('url', models.URLField(verbose_name='news link')),
                ('title', models.CharField(max_length=150, verbose_name='news title')),
                ('short_title', models.CharField(max_length=80, verbose_name='participants')),
                ('section', models.CharField(max_length=20, verbose_name='sport')),
                ('subsection', models.CharField(max_length=80, verbose_name='liga')),
                ('published', models.DateTimeField(verbose_name='published')),
                ('updated', models.DateTimeField(verbose_name='updated')),
                ('crawled', models.DateTimeField(verbose_name='fetched')),
                ('archived', models.CharField(choices=[('archived', 'Archived'), ('fresh', 'Fresh')], max_length=9, verbose_name='archived')),
                ('preamble', models.CharField(max_length=500, null=True, verbose_name='news preamble')),
                ('content', models.TextField(verbose_name='full news content')),
                ('subtable', models.TextField(verbose_name='news subtable')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'newss',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='tip id')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='participants')),
                ('place', models.CharField(db_index=True, max_length=40, verbose_name='liga')),
                ('tip', models.CharField(max_length=60, verbose_name='tip title')),
                ('text', models.TextField(null=True, verbose_name='tip text')),
                ('betting', models.CharField(max_length=32, verbose_name='betting')),
                ('coeff', models.CharField(max_length=6, verbose_name='tip coefficient')),
                ('min_coeff', models.CharField(max_length=6, verbose_name='minimum tip coeff')),
                ('result', models.CharField(max_length=15, verbose_name='tip result')),
                ('due', models.CharField(max_length=8, verbose_name='earnings')),
                ('spread', models.CharField(max_length=8, verbose_name='spread')),
                ('stake', models.CharField(max_length=8, verbose_name='stake')),
                ('success', models.CharField(max_length=12, null=True, verbose_name='tip success')),
                ('tipster', models.CharField(max_length=12, verbose_name='tipster')),
                ('published', models.DateTimeField(db_index=True, null=True, verbose_name='published')),
                ('updated', models.DateTimeField(verbose_name='updated')),
                ('crawled', models.DateTimeField(verbose_name='fetched')),
                ('details_url', models.URLField(verbose_name='tip link')),
                ('archived', models.CharField(choices=[('archived', 'Archived'), ('fresh', 'Fresh')], max_length=9, verbose_name='archived')),
            ],
            options={
                'verbose_name': 'tip',
                'verbose_name_plural': 'tips',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='dz user name')),
                ('password', models.CharField(max_length=64, verbose_name='dz user password')),
                ('is_admin', models.BooleanField(verbose_name='is dz administrator')),
            ],
            options={
                'verbose_name': 'dz user',
                'verbose_name_plural': 'dz users',
            },
        ),
        migrations.AlterIndexTogether(
            name='tip',
            index_together=set([('published', 'archived')]),
        ),
        migrations.AlterIndexTogether(
            name='news',
            index_together=set([('published', 'archived')]),
        ),
    ]
