# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dz_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
