# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='tip',
            name='place',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='published',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Published (Objavleno)'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='User Name'),
        ),
        migrations.AlterIndexTogether(
            name='news',
            index_together=set([('published', 'archived')]),
        ),
        migrations.AlterIndexTogether(
            name='tip',
            index_together=set([('published', 'archived')]),
        ),
    ]
