# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0002_auto_20160513_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawl',
            options={'verbose_name': 'crawl', 'verbose_name_plural': 'crawls'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'newss'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'verbose_name': 'tip', 'verbose_name_plural': 'tips'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'dz user', 'verbose_name_plural': 'dz users'},
        ),
        migrations.AlterField(
            model_name='crawl',
            name='action',
            field=models.CharField(choices=[('news', 'news crawl'), ('tips', 'tips crawl')], max_length=6, verbose_name='crawl target'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='ended',
            field=models.DateTimeField(null=True, verbose_name='ended at'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='host',
            field=models.CharField(max_length=24, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='crawl id'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='ipaddr',
            field=models.CharField(max_length=20, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='news',
            field=models.SmallIntegerField(verbose_name='no. of news'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='pid',
            field=models.CharField(max_length=6, verbose_name='crawler pid'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='started',
            field=models.DateTimeField(verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='status',
            field=models.CharField(max_length=10, verbose_name='crawl status'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='tips',
            field=models.SmallIntegerField(verbose_name='no. of tips'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='type',
            field=models.CharField(choices=[('manual', 'manual crawl'), ('auto', 'auto crawl')], max_length=8, verbose_name='crawl type'),
        ),
        migrations.AlterField(
            model_name='news',
            name='archived',
            field=models.CharField(choices=[('archived', 'Archived'), ('fresh', 'Fresh')], max_length=9, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='full news content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='crawled',
            field=models.DateTimeField(verbose_name='fetched'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='news id'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preamble',
            field=models.CharField(max_length=500, null=True, verbose_name='news preamble'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.CharField(max_length=20, verbose_name='sport'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_title',
            field=models.CharField(max_length=80, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subsection',
            field=models.CharField(max_length=80, verbose_name='liga'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtable',
            field=models.TextField(verbose_name='news subtable'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='news title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(verbose_name='news link'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='archived',
            field=models.CharField(choices=[('archived', 'Archived'), ('fresh', 'Fresh')], max_length=9, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='betting',
            field=models.CharField(max_length=32, verbose_name='betting'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='coeff',
            field=models.CharField(max_length=6, verbose_name='tip coefficient'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='crawled',
            field=models.DateTimeField(verbose_name='fetched'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='details_url',
            field=models.URLField(verbose_name='tip link'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='due',
            field=models.CharField(max_length=8, verbose_name='earnings'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='id',
            field=models.IntegerField(db_column='pk', primary_key=True, serialize=False, verbose_name='tip id'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='min_coeff',
            field=models.CharField(max_length=6, verbose_name='minimum tip coeff'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='place',
            field=models.CharField(db_index=True, max_length=40, verbose_name='liga'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='published',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='result',
            field=models.CharField(max_length=15, verbose_name='tip result'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='spread',
            field=models.CharField(max_length=8, verbose_name='spread'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='stake',
            field=models.CharField(max_length=8, verbose_name='stake'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='success',
            field=models.CharField(max_length=12, null=True, verbose_name='tip success'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(null=True, verbose_name='tip text'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tip',
            field=models.CharField(max_length=60, verbose_name='tip title'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tipster',
            field=models.CharField(max_length=12, verbose_name='tipster'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='updated',
            field=models.DateTimeField(verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(verbose_name='is dz administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='dz user password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='dz user name'),
        ),
    ]
