# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0003_auto_20160824_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='action',
            field=models.CharField(choices=[('news', 'news crawl'), ('tips', 'tips crawl')], db_index=True, max_length=6, verbose_name='crawl target'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='host',
            field=models.CharField(db_index=True, max_length=24, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='type',
            field=models.CharField(choices=[('manual', 'manual crawl'), ('auto', 'auto crawl')], db_index=True, max_length=8, verbose_name='crawl type'),
        ),
        migrations.AlterField(
            model_name='news',
            name='section',
            field=models.CharField(db_index=True, max_length=20, verbose_name='sport'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subsection',
            field=models.CharField(db_index=True, max_length=80, verbose_name='liga'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(db_index=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='tipster',
            field=models.CharField(db_index=True, max_length=12, verbose_name='tipster'),
        ),
    ]
