# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0004_auto_20160828_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='started',
            field=models.DateTimeField(null=True, verbose_name='started at'),
        ),
    ]
