# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0005_auto_20160829_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawl',
            name='news',
            field=models.SmallIntegerField(default=0, verbose_name='no. of news'),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='tips',
            field=models.SmallIntegerField(default=0, verbose_name='no. of tips'),
        ),
    ]
