# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0006_auto_20160830_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawl',
            name='ipaddr',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='news',
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='tips',
        ),
        migrations.AddField(
            model_name='crawl',
            name='count',
            field=models.SmallIntegerField(default=0, verbose_name='no. of items'),
        ),
    ]
