# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0007_auto_20160903_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='start time')),
                ('action', models.CharField(choices=[(b'news', 'news crawl'), (b'tips', 'tips crawl')], max_length=6, verbose_name='action')),
            ],
        ),
    ]
