# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0008_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'job', 'verbose_name_plural': 'schedule'},
        ),
    ]
