---
- hosts: localhost
  become: false
  gather_facts: false
  tags: env
  tasks:
    - lineinfile: dest=../.env create=yes mode=0600 line='{{ item|upper }}="{{ public[item] }}"'
      with_items: '{{ public.keys() | sort }}'
    - lineinfile: dest=../.env create=yes mode=0600 line='{{ item|upper }}="{{ secret[item] }}"'
      with_items: '{{ secret.keys() | sort }}'

- hosts: localhost
  become: true
  become_user: postgres
  gather_facts: false
  tags: db
  tasks:
    - postgresql_db: port={{postgres.port}} name={{postgres.database}}
                     template='template0' encoding='UTF-8'
                     lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8'
    - postgresql_user: port={{postgres.port}} db={{postgres.database}}
                       name={{postgres.username}} password={{postgres.password}}
...
