---
- hosts: localhost
  become: false
  gather_facts: false
  tags: env
  tasks:
    - lineinfile: dest=../.env create=yes mode=0600
                  regexp='^{{ item|upper }}='
                  line='{{ item|upper }}="{{ public[item] }}"'
      with_items: '{{ public.keys() | sort }}'

    - lineinfile: dest=../.env create=yes mode=0600
                  regexp='^{{ item|upper }}='
                  line='{{ item|upper }}="{{ secret[item] }}"'
      with_items: '{{ secret.keys() | sort }}'

- hosts: localhost
  become: true
  gather_facts: false
  tags: install
  tasks:
    - apt: pkg={{item}}
      with_items:
        - gettext  # for translations
        - build-essential
        - libpython-dev
        - libffi-dev
        - libssl-dev
        - libjpeg-dev
        - libxml2-dev
        - libxslt1-dev

- hosts: localhost
  become: true
  become_user: postgres
  gather_facts: false
  tags: db
  tasks:
    - postgresql_db: port={{postgres.port}} name={{postgres.database}}
                     template='template0' encoding='UTF-8'
                     lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8'
    - postgresql_user: port={{postgres.port}} db={{postgres.database}}
                       name={{postgres.username}} password={{postgres.password}}

- hosts: localhost
  gather_facts: false
  tags: npm
  tasks:
    - apt: name=npm
      become: true
    - npm: name={{item}} global=yes
      with_items:
        - webpack
        - webpack-dev-server
        - eslint
        - eslint-config-google
        - sass-lint
      become: true
    # install packages from package.json
    - npm: path={{inventory_dir|dirname}}
      become: false

- hosts: localhost
  become: true
  gather_facts: false
  tags: phantomjs
  vars:
    phantomjs_version: 'phantomjs-2.1.1-linux-x86_64'
  tasks:
    - name: remove broken phantomjs .deb package
      # see http://stackoverflow.com/questions/36770303/phantomjs-with-selenium-unable-to-load-atom-find-element#36800913
      apt: name=phantomjs state=absent

    - name: download phantomjs from official site
      unarchive:
        src: https://bitbucket.org/ariya/phantomjs/downloads/{{phantomjs_version}}.tar.bz2
        dest: /usr/local
        copy: no
        creates: '/usr/local/{{phantomjs_version}}'

    - name: create link to phantomjs binary
      file:
        state: link
        src: ../{{phantomjs_version}}/bin/phantomjs
        dest: /usr/local/bin/phantomjs
...
